#!/bin/sh

remote="$1"
url="$2"

if test "$remote" = "main" && test "$url" = "https://github.com/TeamGalacticraft/Galacticraft"
then
	echo -e "Started running './gradlew test' Gradle task..."

	./gradlew :test
	status=$?

	if test "$status" = 0
	then
		echo -e "\n...test succeeded, proceeding with git push.\n"
	else
		echo -e "\n...test failed, aborting git push.\n"
	fi
fi

exit $status