#!/bin/sh

echo "Started running './gradlew spotlessCheck' Gradle task..."

./gradlew spotlessCheck &>/dev/null
status=$?

if test "$status" = 0
then
	echo -e "...spotlessCheck succeeded, proceeding with git commit.\n"
else
	echo -e "...spotlessCheck failed, aborting git commit.\n"
	echo -e "Started running './gradlew spotlessApply' to fix these violations..."

	./gradlew spotlessApply &>/dev/null
	applied=$?

	if test "$applied" = 0
	then
		echo "...spotlessApply succeeded, stage these changes and re-commit."
	else
		echo "...spotlessApply failed."
	fi
fi

exit $status