#!/bin/sh

remote="$1"
url="$2"

echo "$remote"
echo "$url"

while read local_ref local_oid remote_ref remote_oid
do
	echo "$local_ref"
	echo "$local_oid"
	echo "$remote_ref"
	echo "$remote_oid"

	echo -e "Started running './gradlew test' Gradle task..."

	./gradlew :test
	status=$?

	if test "$status" = 0
	then
		echo -e "\n...test succeeded, proceeding with git push.\n"
	else
		echo -e "\n...test failed, aborting git push.\n"
	fi
done

exit $status