#!/bin/sh

echo "Started running './gradlew spotlessCheck' Gradle task..."

./gradlew spotlessCheck &>/dev/null
status=$?

if test "$status" = 0
then
	echo -e "...spotlessCheck succeeded, proceeding with git commit.\n"
else
	echo -e "...spotlessCheck failed, aborting git commit.\n"
	echo -e "Run './gradlew spotlessApply' to fix these violations.\n"
fi

exit $status