#!/bin/sh

echo -e "Started running './gradlew test' Gradle task...\n"

./gradlew :test
status=$?

if test "$status" = 0
then
	echo -e "...test succeeded, proceeding with git push.\n"
else
	echo -e "...test failed, aborting git push.\n"
fi

exit $status