blank_issues_enabled: true
contact_links:
  - name: Galacticraft Developemnt Discord
    url: https://discord.gg/n3QqhMYyFK
    about: General development of the mod and mod support.
  - name: Galacticraft Community Discord
    url: https://discord.gg/bSZR3bdRW8
    about: Support for addons and a general home of space modding.