blank_issues_enabled: false
contact_links:
  - name: Galacticraft Central Discord
    url: http://discord.galacticraftcentral.com/
    about: Please use this discord for general Galacticraft help and support.
  - name: Galacticraft Development Discord
    url: https://discord.gg/n3QqhMYyFK
    about: Please use this discord to discuss the development of, and help develop Galacticraft.
