package io.github.teamgalacticraft.galacticraft.blocks;

import io.github.teamgalacticraft.galacticraft.Constants;
import io.github.teamgalacticraft.galacticraft.api.blocks.GalacticraftStairsBlock;
import io.github.teamgalacticraft.galacticraft.blocks.decoration.CheeseBlock;
import io.github.teamgalacticraft.galacticraft.blocks.decoration.GratingBlock;
import io.github.teamgalacticraft.galacticraft.blocks.decoration.LightingPanelBlock;
import io.github.teamgalacticraft.galacticraft.blocks.decoration.VacuumGlassBlock;
import io.github.teamgalacticraft.galacticraft.blocks.environment.*;
import io.github.teamgalacticraft.galacticraft.blocks.fluid.CrudeOilBlock;
import io.github.teamgalacticraft.galacticraft.blocks.fluid.FuelBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.AluminumWireBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.basicsolarpanel.BasicSolarPanelBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.basicsolarpanel.BasicSolarPanelPartBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.circuitfabricator.CircuitFabricatorBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.coalgenerator.CoalGeneratorBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.compressor.CompressorBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.energystoragemodule.EnergyStorageModuleBlock;
import io.github.teamgalacticraft.galacticraft.blocks.machines.oxygencollector.OxygenCollectorBlock;
import io.github.teamgalacticraft.galacticraft.blocks.natural.ScorchedRockBlock;
import io.github.teamgalacticraft.galacticraft.blocks.natural.VaporSpoutBlock;
import io.github.teamgalacticraft.galacticraft.blocks.ore.SiliconOreBlock;
import io.github.teamgalacticraft.galacticraft.fluids.GalacticraftFluids;
import net.fabricmc.fabric.api.block.FabricBlockSettings;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.minecraft.block.*;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.block.BlockItem;
import net.minecraft.item.block.WallStandingBlockItem;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;

/**
 * @author <a href="https://github.com/teamgalacticraft">TeamGalacticraft</a>
 */
public class GalacticraftBlocks {
    private static final Marker BLOCKS = MarkerManager.getMarker("Blocks"); // Galacticraft/Blocks

    public static ItemGroup BLOCKS_GROUP = FabricItemGroupBuilder.create(
            new Identifier(Constants.MOD_ID, Constants.Blocks.ITEM_GROUP_BLOCKS))
            // Set the tab icon
            .icon(() -> new ItemStack(GalacticraftBlocks.MOON_TURF_BLOCK))
            .build();


    public static ItemGroup MACHINES_GROUP = FabricItemGroupBuilder.create(
            new Identifier(Constants.MOD_ID, Constants.Blocks.ITEM_GROUP_MACHINES))
            // Set the the tab icon
            .icon(() -> new ItemStack(GalacticraftBlocks.COAL_GENERATOR_BLOCK))
            .build();

    // Blocks
    public static final Block MOON_TURF_BLOCK = new Block(FabricBlockSettings.of(Material.ORGANIC, MaterialColor.LIGHT_GRAY).strength(0.5F, 0.5F).build());
    public static final Block MOON_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.GRAY).strength(1.5F, 6.0F).build());
    public static final Block MOON_DIRT_BLOCK = new Block(FabricBlockSettings.of(Material.EARTH, MaterialColor.LIGHT_GRAY).strength(0.5F, 0.5F).build());
    public static final Block MOON_DUNGEON_BRICKS_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.GRAY).strength(4.0F, 40.0F).build());
    public static final Block MARS_SURFACE_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.DIRT).hardness(2.2F).build());
    public static final Block MARS_SUB_SURFACE_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.RED).hardness(2.6F).build());
    public static final Block MARS_STONE_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.RED).hardness(3.0F).build());
    public static final Block MARS_COBBLESTONE_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.RED).hardness(2.8F).build());
    public static final Block MARS_DUNGEON_BRICKS_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.GREEN).strength(4.0F, 40.0F).build());
    public static final Block DENSE_ICE_BLOCK = new Block(FabricBlockSettings.of(Material.ICE, MaterialColor.ICE).hardness(1.0F).friction(0.90F).sounds(BlockSoundGroup.GLASS).build());
    public static final Block ASTEROID_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.BROWN).hardness(3.0F).build());
    public static final Block ASTEROID_ROCK_BLOCK_1 = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.BROWN).hardness(3.0F).build());
    public static final Block ASTEROID_ROCK_BLOCK_2 = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.BROWN).hardness(3.0F).build());
    public static final Block VENUS_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE).strength(1.5F, 6.0F).build());
    public static final Block VENUS_ROCK_BLOCK_1 = new Block(FabricBlockSettings.of(Material.STONE).strength(1.5F, 6.0F).build());
    public static final Block VENUS_ROCK_BLOCK_2 = new Block(FabricBlockSettings.of(Material.STONE).strength(1.5F, 6.0F).build());
    public static final Block VENUS_ROCK_BLOCK_3 = new Block(FabricBlockSettings.of(Material.STONE).strength(1.5F, 6.0F).build());
    public static final Block VENUS_ROCK_BLOCK_SCORCHED = new ScorchedRockBlock(FabricBlockSettings.of(Material.STONE).strength(1.5F, 6.0F).build());
    public static final Block VOLCANIC_ROCK_BLOCK = new Block(FabricBlockSettings.of(Material.STONE).build().strength(2.2F, 0.5F));
    public static final Block SCORCHED_ROCK_BLOCK = new ScorchedRockBlock(FabricBlockSettings.of(Material.STONE).ticksRandomly().build());
    public static final Block PUMICE_BLOCK = new Block(FabricBlockSettings.of(Material.STONE).resistance(1.0F).build());
    public static final Block VAPOR_SPOUT_BLOCK = new VaporSpoutBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.BROWN).dropsNothing().strength(1.5F, 2.0F).build());
    public static final Block TIN_DECORATION_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 2.0F).build());
    public static final Block TIN_DECORATION_BLOCK_1 = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 2.0F).build());
    public static final Block DARK_DECORATION_BLOCK = new Block(FabricBlockSettings.of(Material.STONE, MaterialColor.BLACK).strength(2.0F, 2.0F).build());
    public static final Block GRATING_BLOCK = new GratingBlock(FabricBlockSettings.of(Material.METAL, MaterialColor.STONE).build().strength(2.5f, 6.0f));
    public static final Block ALUMINUM_WIRE_BLOCK = new AluminumWireBlock(FabricBlockSettings.copy(Blocks.WHITE_WOOL).build());
    public static final Block OXYGEN_PIPE_BLOCK = new Block(FabricBlockSettings.of(Material.WOOL).breakByHand(true).build());
    public static final Block LIGHTING_PANEL_BLOCK_SQUARE = new LightingPanelBlock(FabricBlockSettings.of(Material.METAL).build());
    public static final Block LIGHTING_PANEL_BLOCK_SPOTLIGHT = new LightingPanelBlock(FabricBlockSettings.of(Material.METAL).build(), 3.0f);
    public static final Block LIGHTING_PANEL_BLOCK_LINEAR = new LightingPanelBlock(FabricBlockSettings.of(Material.METAL).build(), 5.0f);
    public static final Block LIGHTING_PANEL_BLOCK_DARK = new LightingPanelBlock(FabricBlockSettings.of(Material.METAL).build(), 1.0f);
    public static final Block LIGHTING_PANEL_BLOCK_DARK_ANGLE = new LightingPanelBlock(FabricBlockSettings.of(Material.METAL).build(), 1.0f);
    public static final Block VACUUM_GLASS_BLOCK = new VacuumGlassBlock(FabricBlockSettings.of(Material.GLASS).build());
    public static final Block VACUUM_GLASS_BLOCK_CLEAR = new VacuumGlassBlock(FabricBlockSettings.of(Material.GLASS).build());
    public static final Block VACUUM_GLASS_BLOCK_TIN = new VacuumGlassBlock(FabricBlockSettings.of(Material.GLASS).build());
    public static final Block VACUUM_GLASS_BLOCK_STRONG = new VacuumGlassBlock(FabricBlockSettings.of(Material.GLASS).build());
    public static final Block WALKWAY_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0f, 5.0f).build());
    public static final Block WALKWAY_BLOCK_WIRE = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0f, 5.0f).build());
    public static final Block WALKWAY_BLOCK_PIPE = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0f, 5.0f).build());
    public static final Block TIN_DECORATION_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 2.0F).build());
    public static final Block TIN_DECORATION_SLAB_BLOCK_1 = new SlabBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 2.0F).build());
    public static final Block DARK_DECORATION_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0f, 2.0f).build());
    public static final Block MARS_COBBLESTONE_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0f, 2.0f).build());
    public static final Block MARS_DUNGEON_BRICKS_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE).strength(5.0f, 5.0f).build());
    public static final Block MOON_DUNGEON_BRICKS_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE).strength(5.0f, 5.0f).build());
    public static final Block MOON_ROCK_SLAB_BLOCK = new SlabBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(5.0f, 5.0f).build());
    public static final Block MOON_ROCK_STAIRS_BLOCK = new GalacticraftStairsBlock(MOON_ROCK_BLOCK.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(5.0f, 5.0f).build());
    public static final Block MOON_DUNGEON_BRICKS_STAIRS_BLOCK = new GalacticraftStairsBlock(MOON_DUNGEON_BRICKS_BLOCK.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.GRAY).strength(5.0f, 5.0f).build());
    public static final Block TIN_DECORATION_BLOCK_STAIRS = new GalacticraftStairsBlock(TIN_DECORATION_BLOCK.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0f, 2.0f).build());
    public static final Block TIN_DECORATION_BLOCK_STAIRS_1 = new GalacticraftStairsBlock(TIN_DECORATION_BLOCK_1.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0f, 2.0f).build());
    public static final Block MARS_DUNGEON_BRICKS_STAIRS_BLOCK = new GalacticraftStairsBlock(MARS_DUNGEON_BRICKS_BLOCK.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.GREEN).strength(5.0f, 5.0f).build());
    public static final Block MARS_COBBLESTONE_STAIRS_BLOCK = new GalacticraftStairsBlock(MARS_COBBLESTONE_BLOCK.getDefaultState(), FabricBlockSettings.of(Material.STONE, MaterialColor.RED).hardness(2.8f).build());
    public static final Block TIN_WALL_BLOCK = new WallBlock(FabricBlockSettings.of(Material.STONE).strength(2.0F, 2.0F).build());
    public static final Block TIN_WALL_BLOCK_1 = new WallBlock(FabricBlockSettings.of(Material.STONE).strength(2.0F, 2.0F).build());
    public static final Block MOON_ROCK_WALL_BLOCK = new WallBlock(FabricBlockSettings.copy(MOON_ROCK_BLOCK).strength(2.0F, 2.0F).build());
    public static final Block MOON_DUNGEON_BRICKS_WALL_BLOCK = new WallBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.GRAY).strength(5.0F, 5.0F).build());
    public static final Block MARS_COBBLESTONE_WALL_BLOCK = new WallBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 2.0F).build());
    public static final Block MARS_DUNGEON_BRICKS_WALL_BLOCK = new WallBlock(FabricBlockSettings.of(Material.STONE, MaterialColor.GREEN).strength(5.0F, 5.0F).build());
    public static final Block COPPER_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block TIN_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block ALUMINUM_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block SILICON_ORE_BLOCK = new SiliconOreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block ASTEROID_ALUMINUM_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block CHEESE_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block CHEESE_BLOCK = new CheeseBlock(FabricBlockSettings.of(Material.CAKE).build());
    public static final Block MOON_COPPER_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block MARS_COPPER_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block DESH_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block ILMENITE_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block MARS_IRON_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block ASTEROID_IRON_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block MOON_TIN_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block MARS_TIN_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block GALENA_ORE_BLOCK = new OreBlock(FabricBlockSettings.of(Material.STONE).strength(5.0F, 3.0F).build());
    public static final Block COPPER_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block TIN_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block ALUMINUM_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block SILICON_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block SOLID_METEORIC_IRON_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block DESH_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block TITANIUM_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block LEAD_BLOCK = new Block(FabricBlockSettings.of(Material.METAL).strength(5.0F, 6.0F).build());
    public static final Block UNLIT_TORCH_BLOCK = new UnlitTorchBlock(FabricBlockSettings.copy(Blocks.TORCH).lightLevel(0).build());
    public static final Block GLOWSTONE_TORCH_BLOCK = new GlowstoneTorchBlock(FabricBlockSettings.copy(Blocks.TORCH).lightLevel(15).build());
    public static final Block GLOWSTONE_WALL_TORCH_BLOCK = new GlowstoneWallTorchBlock(FabricBlockSettings.copy(Blocks.TORCH).lightLevel(15).dropsLike(GLOWSTONE_TORCH_BLOCK).build());
    public static final Block CAVERNOUS_VINE_BLOCK = new CavernousVineBlock(FabricBlockSettings.of(Material.CACTUS, MaterialColor.GREEN).dropsNothing().noCollision().lightLevel(0).build());
    public static final Block POISONOUS_CAVERNOUS_VINE_BLOCK = new CavernousVineBlockPoisonous(FabricBlockSettings.of(Material.CACTUS, MaterialColor.GREEN).dropsNothing().noCollision().lightLevel(3).build());
    public static final Block MOON_BERRY_BUSH_BLOCK = new MoonBerryBushBlock(FabricBlockSettings.of(Material.PLANT, MaterialColor.GREEN).dropsNothing().noCollision().lightLevel(3).build());

    // Machines
    public static final Block CIRCUIT_FABRICATOR_BLOCK = new CircuitFabricatorBlock(FabricBlockSettings.of(Material.METAL).build());
    public static final Block COMPRESSOR_BLOCK = new CompressorBlock(FabricBlockSettings.of(Material.METAL).build());
    public static final Block COAL_GENERATOR_BLOCK = new CoalGeneratorBlock(FabricBlockSettings.of(Material.METAL).build());
    public static final Block BASIC_SOLAR_PANEL_BLOCK = new BasicSolarPanelBlock(FabricBlockSettings.of(Material.METAL).strength(1.0F, 3600000.0F).sounds(BlockSoundGroup.METAL).build());
    public static final Block BASIC_SOLAR_PANEL_PART_BLOCK = new BasicSolarPanelPartBlock(FabricBlockSettings.of(Material.METAL).strength(-1.0F, 3600000.0F).dropsNothing().build());
    public static final Block ENERGY_STORAGE_MODULE_BLOCK = new EnergyStorageModuleBlock(FabricBlockSettings.of(Material.METAL).build());
    public static final Block OXYGEN_COLLECTOR_BLOCK = new OxygenCollectorBlock(FabricBlockSettings.of(Material.METAL).build());

    // Liquids
    public static final Block CRUDE_OIL_BLOCK = new CrudeOilBlock(GalacticraftFluids.STILL_CRUDE_OIL, FabricBlockSettings.of(Material.WATER).noCollision().dropsNothing().resistance(100.0F).build());
    public static final Block FUEL_BLOCK = new FuelBlock(GalacticraftFluids.STILL_FUEL, FabricBlockSettings.of(Material.WATER).noCollision().dropsNothing().resistance(100.0F).build());

    // Block Items
    public static final BlockItem MOON_TURF_BLOCK_ITEM = new BlockItem(MOON_TURF_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_ROCK_BLOCK_ITEM = new BlockItem(MOON_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_DIRT_BLOCK_ITEM = new BlockItem(MOON_DIRT_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_DUNGEON_BRICKS_BLOCK_ITEM = new BlockItem(MOON_DUNGEON_BRICKS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_SURFACE_ROCK_BLOCK_ITEM = new BlockItem(MARS_SURFACE_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_SUB_SURFACE_ROCK_BLOCK_ITEM = new BlockItem(MARS_SUB_SURFACE_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_STONE_BLOCK_ITEM = new BlockItem(MARS_STONE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_COBBLESTONE_BLOCK_ITEM = new BlockItem(MARS_COBBLESTONE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_DUNGEON_BRICKS_BLOCK_ITEM = new BlockItem(MARS_DUNGEON_BRICKS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem DENSE_ICE_BLOCK_ITEM = new BlockItem(DENSE_ICE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ASTEROID_ROCK_BLOCK_ITEM = new BlockItem(ASTEROID_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ASTEROID_ROCK_BLOCK_ITEM_1 = new BlockItem(ASTEROID_ROCK_BLOCK_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ASTEROID_ROCK_BLOCK_ITEM_2 = new BlockItem(ASTEROID_ROCK_BLOCK_2, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VENUS_ROCK_BLOCK_ITEM = new BlockItem(VENUS_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VENUS_ROCK_BLOCK_ITEM_1 = new BlockItem(VENUS_ROCK_BLOCK_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VENUS_ROCK_BLOCK_ITEM_2 = new BlockItem(VENUS_ROCK_BLOCK_2, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VENUS_ROCK_BLOCK_ITEM_3 = new BlockItem(VENUS_ROCK_BLOCK_3, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VENUS_ROCK_BLOCK_ITEM_SCORCHED = new BlockItem(VENUS_ROCK_BLOCK_SCORCHED, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VOLCANIC_ROCK_BLOCK_ITEM = new BlockItem(VOLCANIC_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem SCORCHED_ROCK_BLOCK_ITEM = new BlockItem(SCORCHED_ROCK_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem PUMICE_BLOCK_ITEM = new BlockItem(PUMICE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VAPOR_SPOUT_BLOCK_ITEM = new BlockItem(VAPOR_SPOUT_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem COPPER_ORE_BLOCK_ITEM = new BlockItem(COPPER_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_ORE_BLOCK_ITEM = new BlockItem(TIN_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ALUMINUM_ORE_BLOCK_ITEM = new BlockItem(ALUMINUM_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem SILICON_ORE_BLOCK_ITEM = new BlockItem(SILICON_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ASTEROID_ALUMINUM_ORE_BLOCK_ITEM = new BlockItem(ASTEROID_ALUMINUM_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem CHEESE_ORE_BLOCK_ITEM = new BlockItem(CHEESE_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem CHEESE_BLOCK_ITEM = new BlockItem(CHEESE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_COPPER_ORE_BLOCK_ITEM = new BlockItem(MOON_COPPER_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_COPPER_ORE_BLOCK_ITEM = new BlockItem(MARS_COPPER_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem DESH_ORE_BLOCK_ITEM = new BlockItem(DESH_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ILMENITE_ORE_BLOCK_ITEM = new BlockItem(ILMENITE_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_IRON_ORE_BLOCK_ITEM = new BlockItem(MARS_IRON_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ASTEROID_IRON_ORE_BLOCK_ITEM = new BlockItem(ASTEROID_IRON_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_TIN_ORE_BLOCK_ITEM = new BlockItem(MOON_TIN_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_TIN_ORE_BLOCK_ITEM = new BlockItem(MARS_TIN_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem GALENA_ORE_BLOCK_ITEM = new BlockItem(GALENA_ORE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem COPPER_BLOCK_ITEM = new BlockItem(COPPER_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_BLOCK_ITEM = new BlockItem(TIN_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ALUMINUM_BLOCK_ITEM = new BlockItem(ALUMINUM_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem SILICON_BLOCK_ITEM = new BlockItem(SILICON_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem SOLID_METEORIC_IRON_BLOCK_ITEM = new BlockItem(SOLID_METEORIC_IRON_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem DESH_BLOCK_ITEM = new BlockItem(DESH_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TITANIUM_BLOCK_ITEM = new BlockItem(TITANIUM_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LEAD_BLOCK_ITEM = new BlockItem(LEAD_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_BLOCK_ITEM = new BlockItem(TIN_DECORATION_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_BLOCK_ITEM_1 = new BlockItem(TIN_DECORATION_BLOCK_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem DARK_DECORATION_BLOCK_ITEM = new BlockItem(DARK_DECORATION_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem GRATING_BLOCK_ITEM = new BlockItem(GRATING_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem ALUMINUM_WIRE_BLOCK_ITEM = new BlockItem(ALUMINUM_WIRE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem OXYGEN_PIPE_BLOCK_ITEM = new BlockItem(OXYGEN_PIPE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LIGHTING_PANEL_BLOCK_SQUARE_ITEM = new BlockItem(LIGHTING_PANEL_BLOCK_SQUARE, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LIGHTING_PANEL_BLOCK_SPOTLIGHT_ITEM = new BlockItem(LIGHTING_PANEL_BLOCK_SPOTLIGHT, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LIGHTING_PANEL_BLOCK_LINEAR_ITEM = new BlockItem(LIGHTING_PANEL_BLOCK_LINEAR, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LIGHTING_PANEL_BLOCK_DARK_ITEM = new BlockItem(LIGHTING_PANEL_BLOCK_DARK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem LIGHTING_PANEL_BLOCK_DARK_ANGLE_ITEM = new BlockItem(LIGHTING_PANEL_BLOCK_DARK_ANGLE, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VACUUM_GLASS_BLOCK_ITEM = new BlockItem(VACUUM_GLASS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VACUUM_GLASS_BLOCK_CLEAR_ITEM = new BlockItem(VACUUM_GLASS_BLOCK_CLEAR, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VACUUM_GLASS_BLOCK_TIN_ITEM = new BlockItem(VACUUM_GLASS_BLOCK_TIN, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem VACUUM_GLASS_BLOCK_STRONG_ITEM = new BlockItem(VACUUM_GLASS_BLOCK_STRONG, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem WALKWAY_BLOCK_ITEM = new BlockItem(WALKWAY_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem WALKWAY_BLOCK_WIRE_ITEM = new BlockItem(WALKWAY_BLOCK_WIRE, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem WALKWAY_BLOCK_PIPE_ITEM = new BlockItem(WALKWAY_BLOCK_PIPE, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_SLAB_BLOCK_ITEM = new BlockItem(TIN_DECORATION_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_SLAB_BLOCK_ITEM_1 = new BlockItem(TIN_DECORATION_SLAB_BLOCK_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem DARK_DECORATION_SLAB_BLOCK_ITEM = new BlockItem(DARK_DECORATION_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_COBBLESTONE_SLAB_BLOCK_ITEM = new BlockItem(MARS_COBBLESTONE_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_DUNGEON_BRICKS_SLAB_BLOCK_ITEM = new BlockItem(MARS_DUNGEON_BRICKS_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_DUNGEON_BRICKS_SLAB_BLOCK_ITEM = new BlockItem(MOON_DUNGEON_BRICKS_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_ROCK_SLAB_BLOCK_ITEM = new BlockItem(MOON_ROCK_SLAB_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_ROCK_STAIRS_BLOCK_ITEM = new BlockItem(MOON_ROCK_STAIRS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_DUNGEON_BRICKS_STAIRS_BLOCK_ITEM = new BlockItem(MOON_DUNGEON_BRICKS_STAIRS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_STAIRS_BLOCK_ITEM = new BlockItem(TIN_DECORATION_BLOCK_STAIRS, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_DECORATION_STAIRS_BLOCK_ITEM_1 = new BlockItem(TIN_DECORATION_BLOCK_STAIRS_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_DUNGEON_BRICKS_STAIRS_BLOCK_ITEM = new BlockItem(MARS_DUNGEON_BRICKS_STAIRS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_COBBLESTONE_STAIRS_BLOCK_ITEM = new BlockItem(MARS_COBBLESTONE_STAIRS_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_WALL_BLOCK_ITEM = new BlockItem(TIN_WALL_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem TIN_WALL_BLOCK_ITEM_1 = new BlockItem(TIN_WALL_BLOCK_1, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_ROCK_WALL_BLOCK_ITEM = new BlockItem(MOON_ROCK_WALL_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_DUNGEON_BRICKS_WALL_BLOCK_ITEM = new BlockItem(MOON_DUNGEON_BRICKS_WALL_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_COBBLESTONE_WALL_BLOCK_ITEM = new BlockItem(MARS_COBBLESTONE_WALL_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MARS_DUNGEON_BRICKS_WALL_BLOCK_ITEM = new BlockItem(MARS_DUNGEON_BRICKS_WALL_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem UNLIT_TORCH_BLOCK_ITEM = new BlockItem(UNLIT_TORCH_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem GLOWSTONE_TORCH_BLOCK_ITEM = new WallStandingBlockItem(GLOWSTONE_TORCH_BLOCK, GLOWSTONE_WALL_TORCH_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem CAVERNOUS_VINE_BLOCK_ITEM = new BlockItem(CAVERNOUS_VINE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem POISONOUS_CAVERNOUS_VINE_BLOCK_ITEM = new BlockItem(POISONOUS_CAVERNOUS_VINE_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));
    public static final BlockItem MOON_BERRY_BUSH_BLOCK_ITEM = new BlockItem(MOON_BERRY_BUSH_BLOCK, new Item.Settings().itemGroup(BLOCKS_GROUP));

    public static final BlockItem CRUDE_OIL_BLOCK_ITEM = new BlockItem(CRUDE_OIL_BLOCK, new Item.Settings());

    public static final BlockItem CIRCUIT_FABRICATOR_BLOCK_ITEM = new BlockItem(CIRCUIT_FABRICATOR_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));
    public static final BlockItem COMPRESSOR_BLOCK_ITEM = new BlockItem(COMPRESSOR_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));
    public static final BlockItem COAL_GENERATOR_BLOCK_ITEM = new BlockItem(COAL_GENERATOR_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));
    public static final BlockItem BASIC_SOLAR_PANEL_BLOCK_ITEM = new BlockItem(BASIC_SOLAR_PANEL_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));
    public static final BlockItem BASIC_SOLAR_PANEL_PART_BLOCK_ITEM = new BlockItem(BASIC_SOLAR_PANEL_PART_BLOCK, new Item.Settings());
    public static final BlockItem ENERGY_STORAGE_MODULE_BLOCK_ITEM = new BlockItem(ENERGY_STORAGE_MODULE_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));
    public static final BlockItem OXYGEN_COLLECTOR_BLOCK_ITEM = new BlockItem(OXYGEN_COLLECTOR_BLOCK, new Item.Settings().itemGroup(MACHINES_GROUP));

    public static void register() {
        // Register Blocks
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_TURF), MOON_TURF_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK), MOON_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DIRT), MOON_DIRT_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_BLOCK), MOON_DUNGEON_BRICKS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_SURFACE_ROCK_BLOCK), MARS_SURFACE_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_SUB_SURFACE_ROCK_BLOCK), MARS_SUB_SURFACE_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_STONE), MARS_STONE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE), MARS_COBBLESTONE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_BLOCK), MARS_DUNGEON_BRICKS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.DENSE_ICE_BLOCK), DENSE_ICE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK), ASTEROID_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK_1), ASTEROID_ROCK_BLOCK_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK_2), ASTEROID_ROCK_BLOCK_2);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK), VENUS_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_1), VENUS_ROCK_BLOCK_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_2), VENUS_ROCK_BLOCK_2);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_3), VENUS_ROCK_BLOCK_3);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_SCORCHED), VENUS_ROCK_BLOCK_SCORCHED);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VOLCANIC_ROCK_BLOCK), VOLCANIC_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.SCORCHED_ROCK_BLOCK), SCORCHED_ROCK_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.PUMICE_BLOCK), PUMICE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VAPOR_SPOUT_BLOCK), VAPOR_SPOUT_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_BLOCK), TIN_DECORATION_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_BLOCK_1), TIN_DECORATION_BLOCK_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_WALL), TIN_WALL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_WALL_1), TIN_WALL_BLOCK_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.COPPER_ORE_BLOCK), COPPER_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_ORE_BLOCK), TIN_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_ORE_BLOCK), ALUMINUM_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.SILICON_ORE_BLOCK), SILICON_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.COPPER_BLOCK), COPPER_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_BLOCK), TIN_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_BLOCK), ALUMINUM_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.SILICON_BLOCK), SILICON_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ALUMINUM_ORE_BLOCK), ASTEROID_ALUMINUM_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.CHEESE_ORE_BLOCK), CHEESE_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_COPPER_ORE_BLOCK), MOON_COPPER_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COPPER_ORE_BLOCK), MARS_COPPER_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.DESH_ORE_BLOCK), DESH_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ILMENITE_ORE_BLOCK), ILMENITE_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_IRON_ORE_BLOCK), MARS_IRON_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_IRON_ORE_BLOCK), ASTEROID_IRON_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_TIN_ORE_BLOCK), MARS_TIN_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_TIN_ORE_BLOCK), MOON_TIN_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.GALENA_ORE_BLOCK), GALENA_ORE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.SOLID_METEORIC_IRON_BLOCK), SOLID_METEORIC_IRON_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.DESH_BLOCK), DESH_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TITANIUM_BLOCK), TITANIUM_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LEAD_BLOCK), LEAD_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.DARK_DECORATION_BLOCK), DARK_DECORATION_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.GRATING_BLOCK), GRATING_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_WIRE_BLOCK), ALUMINUM_WIRE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.OXYGEN_PIPE_BLOCK), OXYGEN_PIPE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_SQUARE), LIGHTING_PANEL_BLOCK_SQUARE);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_SPOTLIGHT), LIGHTING_PANEL_BLOCK_SPOTLIGHT);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_LINEAR), LIGHTING_PANEL_BLOCK_LINEAR);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_DARK), LIGHTING_PANEL_BLOCK_DARK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_DARK_ANGLE), LIGHTING_PANEL_BLOCK_DARK_ANGLE);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK), VACUUM_GLASS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_CLEAR), VACUUM_GLASS_BLOCK_CLEAR);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_TIN), VACUUM_GLASS_BLOCK_TIN);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_STRONG), VACUUM_GLASS_BLOCK_STRONG);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK), WALKWAY_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK_WIRE), WALKWAY_BLOCK_WIRE);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK_PIPE), WALKWAY_BLOCK_PIPE);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_SLAB), TIN_DECORATION_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_SLAB_1), TIN_DECORATION_SLAB_BLOCK_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.DARK_DECORATION_SLAB), DARK_DECORATION_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_SLAB_BLOCK), MARS_COBBLESTONE_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_SLAB_BLOCK), MARS_DUNGEON_BRICKS_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_SLAB_BLOCK), MOON_DUNGEON_BRICKS_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_SLAB_BLOCK), MOON_ROCK_SLAB_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_STAIRS), MOON_ROCK_STAIRS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_STAIRS), MOON_DUNGEON_BRICKS_STAIRS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_STAIRS), TIN_DECORATION_BLOCK_STAIRS);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_STAIRS_1), TIN_DECORATION_BLOCK_STAIRS_1);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_STAIRS), MARS_DUNGEON_BRICKS_STAIRS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_STAIRS), MARS_COBBLESTONE_STAIRS_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_WALL), MOON_ROCK_WALL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_WALL), MOON_DUNGEON_BRICKS_WALL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_WALL), MARS_COBBLESTONE_WALL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_WALL), MARS_DUNGEON_BRICKS_WALL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.CHEESE_BLOCK), CHEESE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.UNLIT_TORCH), UNLIT_TORCH_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.GLOWSTONE_TORCH), GLOWSTONE_TORCH_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.GLOWSTONE_WALL_TORCH), GLOWSTONE_WALL_TORCH_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.CAVERNOUS_VINE_BLOCK), CAVERNOUS_VINE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.POISONOUS_CAVERNOUS_VINE_BLOCK), POISONOUS_CAVERNOUS_VINE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_BERRY_BUSH_BLOCK), MOON_BERRY_BUSH_BLOCK);

        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.CRUDE_OIL_BLOCK), CRUDE_OIL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.FUEL_BLOCK), FUEL_BLOCK);

        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.CIRCUIT_FABRICATOR_BLOCK), CIRCUIT_FABRICATOR_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.COMPRESSOR_BLOCK), COMPRESSOR_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.COAL_GENERATOR_BLOCK), COAL_GENERATOR_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.BASIC_SOLAR_PANEL_BLOCK), BASIC_SOLAR_PANEL_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.BASIC_SOLAR_PANEL_PART_BLOCK), BASIC_SOLAR_PANEL_PART_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.ENERGY_STORAGE_MODULE_BLOCK), ENERGY_STORAGE_MODULE_BLOCK);
        Registry.register(Registry.BLOCK, new Identifier(Constants.MOD_ID, Constants.Blocks.OXYGEN_COLLECTOR_BLOCK), OXYGEN_COLLECTOR_BLOCK);

        // Register Block items
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_TURF), MOON_TURF_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK), MOON_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DIRT), MOON_DIRT_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_BLOCK), MOON_DUNGEON_BRICKS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_SURFACE_ROCK_BLOCK), MARS_SURFACE_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_SUB_SURFACE_ROCK_BLOCK), MARS_SUB_SURFACE_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_STONE), MARS_STONE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE), MARS_COBBLESTONE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_BLOCK), MARS_DUNGEON_BRICKS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.DENSE_ICE_BLOCK), DENSE_ICE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK), ASTEROID_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK_1), ASTEROID_ROCK_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ROCK_BLOCK_2), ASTEROID_ROCK_BLOCK_ITEM_2);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK), VENUS_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_1), VENUS_ROCK_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_2), VENUS_ROCK_BLOCK_ITEM_2);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_3), VENUS_ROCK_BLOCK_ITEM_3);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VENUS_ROCK_BLOCK_SCORCHED), VENUS_ROCK_BLOCK_ITEM_SCORCHED);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VOLCANIC_ROCK_BLOCK), VOLCANIC_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.SCORCHED_ROCK_BLOCK), SCORCHED_ROCK_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.PUMICE_BLOCK), PUMICE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VAPOR_SPOUT_BLOCK), VAPOR_SPOUT_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_BLOCK), TIN_DECORATION_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_BLOCK_1), TIN_DECORATION_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_WALL), TIN_WALL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_WALL_1), TIN_WALL_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.COPPER_ORE_BLOCK), COPPER_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_ORE_BLOCK), TIN_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_ORE_BLOCK), ALUMINUM_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.SILICON_ORE_BLOCK), SILICON_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.COPPER_BLOCK), COPPER_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_BLOCK), TIN_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_BLOCK), ALUMINUM_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.SILICON_BLOCK), SILICON_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_ALUMINUM_ORE_BLOCK), ASTEROID_ALUMINUM_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.CHEESE_ORE_BLOCK), CHEESE_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_COPPER_ORE_BLOCK), MOON_COPPER_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COPPER_ORE_BLOCK), MARS_COPPER_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.DESH_ORE_BLOCK), DESH_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ILMENITE_ORE_BLOCK), ILMENITE_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_IRON_ORE_BLOCK), MARS_IRON_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ASTEROID_IRON_ORE_BLOCK), ASTEROID_IRON_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_TIN_ORE_BLOCK), MARS_TIN_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_TIN_ORE_BLOCK), MOON_TIN_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.GALENA_ORE_BLOCK), GALENA_ORE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.SOLID_METEORIC_IRON_BLOCK), SOLID_METEORIC_IRON_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.DESH_BLOCK), DESH_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TITANIUM_BLOCK), TITANIUM_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LEAD_BLOCK), LEAD_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.DARK_DECORATION_BLOCK), DARK_DECORATION_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.GRATING_BLOCK), GRATING_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ALUMINUM_WIRE_BLOCK), ALUMINUM_WIRE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.OXYGEN_PIPE_BLOCK), OXYGEN_PIPE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_SQUARE), LIGHTING_PANEL_BLOCK_SQUARE_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_SPOTLIGHT), LIGHTING_PANEL_BLOCK_SPOTLIGHT_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_LINEAR), LIGHTING_PANEL_BLOCK_LINEAR_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_DARK), LIGHTING_PANEL_BLOCK_DARK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.LIGHTING_PANEL_BLOCK_DARK_ANGLE), LIGHTING_PANEL_BLOCK_DARK_ANGLE_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK), VACUUM_GLASS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_CLEAR), VACUUM_GLASS_BLOCK_CLEAR_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_TIN), VACUUM_GLASS_BLOCK_TIN_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.VACUUM_GLASS_BLOCK_STRONG), VACUUM_GLASS_BLOCK_STRONG_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK), WALKWAY_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK_WIRE), WALKWAY_BLOCK_WIRE_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.WALKWAY_BLOCK_PIPE), WALKWAY_BLOCK_PIPE_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_SLAB), TIN_DECORATION_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_SLAB_1), TIN_DECORATION_SLAB_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.DARK_DECORATION_SLAB), DARK_DECORATION_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_SLAB_BLOCK), MARS_COBBLESTONE_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_SLAB_BLOCK), MARS_DUNGEON_BRICKS_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_SLAB_BLOCK), MOON_DUNGEON_BRICKS_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_SLAB_BLOCK), MOON_ROCK_SLAB_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_STAIRS), MOON_ROCK_STAIRS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_STAIRS), MOON_DUNGEON_BRICKS_STAIRS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_STAIRS), TIN_DECORATION_STAIRS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.TIN_DECORATION_STAIRS_1), TIN_DECORATION_STAIRS_BLOCK_ITEM_1);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_STAIRS), MARS_DUNGEON_BRICKS_STAIRS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_STAIRS), MARS_COBBLESTONE_STAIRS_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_ROCK_WALL), MOON_ROCK_WALL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_DUNGEON_BRICKS_WALL), MOON_DUNGEON_BRICKS_WALL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_COBBLESTONE_WALL), MARS_COBBLESTONE_WALL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MARS_DUNGEON_BRICKS_WALL), MARS_DUNGEON_BRICKS_WALL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.CHEESE_BLOCK), CHEESE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.UNLIT_TORCH), UNLIT_TORCH_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.GLOWSTONE_TORCH), GLOWSTONE_TORCH_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.CAVERNOUS_VINE_BLOCK), CAVERNOUS_VINE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.POISONOUS_CAVERNOUS_VINE_BLOCK), POISONOUS_CAVERNOUS_VINE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.MOON_BERRY_BUSH_BLOCK), MOON_BERRY_BUSH_BLOCK_ITEM);

        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.CRUDE_OIL_BLOCK), CRUDE_OIL_BLOCK_ITEM);

        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.CIRCUIT_FABRICATOR_BLOCK), CIRCUIT_FABRICATOR_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.COMPRESSOR_BLOCK), COMPRESSOR_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.COAL_GENERATOR_BLOCK), COAL_GENERATOR_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.BASIC_SOLAR_PANEL_BLOCK), BASIC_SOLAR_PANEL_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.BASIC_SOLAR_PANEL_PART_BLOCK), BASIC_SOLAR_PANEL_PART_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.ENERGY_STORAGE_MODULE_BLOCK), ENERGY_STORAGE_MODULE_BLOCK_ITEM);
        Registry.register(Registry.ITEM, new Identifier(Constants.MOD_ID, Constants.Blocks.OXYGEN_COLLECTOR_BLOCK), OXYGEN_COLLECTOR_BLOCK_ITEM);
    }
}