/*
 * Copyright (c) 2023 Team Galacticraft
 *
 * Licensed under the MIT license.
 * See LICENSE file in the project root for details.
 */

package micdoodle8.mods.miccore;

import com.google.common.eventbus.EventBus;
import java.util.Arrays;
import micdoodle8.mods.galacticraft.core.Constants;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;

public class MicdoodleModContainer extends DummyModContainer
{

    public MicdoodleModContainer()
    {
        super(new ModMetadata());
        ModMetadata meta = this.getMetadata();
        meta.modId = "micdoodlecore";
        meta.version = Constants.VERSION;
        meta.name = "Micdoodle8 Core";
        meta.description = "Provides core features of Micdoodle8's mods";
        meta.authorList = Arrays.asList("micdoodle8, radfast");
        meta.url = "https://www.micdoodle8.com/";
        meta.autogenerated = false;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller)
    {
        bus.register(this);
        return true;
    }
}
